/*
 * This file is generated by jOOQ.
 */
package com.eldorado.cleaningservices.infrastructure.repository.jooq;


import com.eldorado.cleaningservices.infrastructure.repository.jooq.tables.Building;
import com.eldorado.cleaningservices.infrastructure.repository.jooq.tables.Orders;
import com.eldorado.cleaningservices.infrastructure.repository.jooq.tables.Person;
import com.eldorado.cleaningservices.infrastructure.repository.jooq.tables.Service;
import com.eldorado.cleaningservices.infrastructure.repository.jooq.tables.ServiceOrder;
import com.eldorado.cleaningservices.infrastructure.repository.jooq.tables.ServicePack;
import com.eldorado.cleaningservices.infrastructure.repository.jooq.tables.ServicesInPack;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Building.BUILDING,
            Orders.ORDERS,
            Person.PERSON,
            Service.SERVICE,
            ServiceOrder.SERVICE_ORDER,
            ServicePack.SERVICE_PACK,
            ServicesInPack.SERVICES_IN_PACK);
    }
}
