/*
 * This file is generated by jOOQ.
 */
package com.eldorado.cleaningservices.infrastructure.repository.jooq.tables;


import com.eldorado.cleaningservices.infrastructure.repository.jooq.DefaultSchema;
import com.eldorado.cleaningservices.infrastructure.repository.jooq.tables.records.ServicesInPackRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServicesInPack extends TableImpl<ServicesInPackRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>SERVICES_IN_PACK</code>
     */
    public static final ServicesInPack SERVICES_IN_PACK = new ServicesInPack();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ServicesInPackRecord> getRecordType() {
        return ServicesInPackRecord.class;
    }

    /**
     * The column <code>SERVICES_IN_PACK.service_id</code>.
     */
    public final TableField<ServicesInPackRecord, Integer> SERVICE_ID = createField(DSL.name("service_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>SERVICES_IN_PACK.service_pack_id</code>.
     */
    public final TableField<ServicesInPackRecord, Integer> SERVICE_PACK_ID = createField(DSL.name("service_pack_id"), SQLDataType.INTEGER, this, "");

    private ServicesInPack(Name alias, Table<ServicesInPackRecord> aliased) {
        this(alias, aliased, null);
    }

    private ServicesInPack(Name alias, Table<ServicesInPackRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>SERVICES_IN_PACK</code> table reference
     */
    public ServicesInPack(String alias) {
        this(DSL.name(alias), SERVICES_IN_PACK);
    }

    /**
     * Create an aliased <code>SERVICES_IN_PACK</code> table reference
     */
    public ServicesInPack(Name alias) {
        this(alias, SERVICES_IN_PACK);
    }

    /**
     * Create a <code>SERVICES_IN_PACK</code> table reference
     */
    public ServicesInPack() {
        this(DSL.name("SERVICES_IN_PACK"), null);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public ServicesInPack as(String alias) {
        return new ServicesInPack(DSL.name(alias), this);
    }

    @Override
    public ServicesInPack as(Name alias) {
        return new ServicesInPack(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ServicesInPack rename(String name) {
        return new ServicesInPack(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ServicesInPack rename(Name name) {
        return new ServicesInPack(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
