/*
 * This file is generated by jOOQ.
 */
package com.eldorado.cleaningservices.infrastructure.repository.jooq.tables.records;


import com.eldorado.cleaningservices.infrastructure.repository.jooq.tables.ServiceOrder;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServiceOrderRecord extends UpdatableRecordImpl<ServiceOrderRecord> implements Record8<Integer, LocalDate, LocalDate, String, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>SERVICE_ORDER.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>SERVICE_ORDER.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>SERVICE_ORDER.start_date</code>.
     */
    public void setStartDate(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>SERVICE_ORDER.start_date</code>.
     */
    public LocalDate getStartDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>SERVICE_ORDER.end_date</code>.
     */
    public void setEndDate(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>SERVICE_ORDER.end_date</code>.
     */
    public LocalDate getEndDate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>SERVICE_ORDER.finished_picture</code>.
     */
    public void setFinishedPicture(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>SERVICE_ORDER.finished_picture</code>.
     */
    public String getFinishedPicture() {
        return (String) get(3);
    }

    /**
     * Setter for <code>SERVICE_ORDER.person_id</code>.
     */
    public void setPersonId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>SERVICE_ORDER.person_id</code>.
     */
    public Integer getPersonId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>SERVICE_ORDER.building_id</code>.
     */
    public void setBuildingId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>SERVICE_ORDER.building_id</code>.
     */
    public Integer getBuildingId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>SERVICE_ORDER.service_id</code>.
     */
    public void setServiceId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>SERVICE_ORDER.service_id</code>.
     */
    public Integer getServiceId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>SERVICE_ORDER.order_id</code>.
     */
    public void setOrderId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>SERVICE_ORDER.order_id</code>.
     */
    public Integer getOrderId() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, LocalDate, LocalDate, String, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, LocalDate, LocalDate, String, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ServiceOrder.SERVICE_ORDER.ID;
    }

    @Override
    public Field<LocalDate> field2() {
        return ServiceOrder.SERVICE_ORDER.START_DATE;
    }

    @Override
    public Field<LocalDate> field3() {
        return ServiceOrder.SERVICE_ORDER.END_DATE;
    }

    @Override
    public Field<String> field4() {
        return ServiceOrder.SERVICE_ORDER.FINISHED_PICTURE;
    }

    @Override
    public Field<Integer> field5() {
        return ServiceOrder.SERVICE_ORDER.PERSON_ID;
    }

    @Override
    public Field<Integer> field6() {
        return ServiceOrder.SERVICE_ORDER.BUILDING_ID;
    }

    @Override
    public Field<Integer> field7() {
        return ServiceOrder.SERVICE_ORDER.SERVICE_ID;
    }

    @Override
    public Field<Integer> field8() {
        return ServiceOrder.SERVICE_ORDER.ORDER_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public LocalDate component2() {
        return getStartDate();
    }

    @Override
    public LocalDate component3() {
        return getEndDate();
    }

    @Override
    public String component4() {
        return getFinishedPicture();
    }

    @Override
    public Integer component5() {
        return getPersonId();
    }

    @Override
    public Integer component6() {
        return getBuildingId();
    }

    @Override
    public Integer component7() {
        return getServiceId();
    }

    @Override
    public Integer component8() {
        return getOrderId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public LocalDate value2() {
        return getStartDate();
    }

    @Override
    public LocalDate value3() {
        return getEndDate();
    }

    @Override
    public String value4() {
        return getFinishedPicture();
    }

    @Override
    public Integer value5() {
        return getPersonId();
    }

    @Override
    public Integer value6() {
        return getBuildingId();
    }

    @Override
    public Integer value7() {
        return getServiceId();
    }

    @Override
    public Integer value8() {
        return getOrderId();
    }

    @Override
    public ServiceOrderRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ServiceOrderRecord value2(LocalDate value) {
        setStartDate(value);
        return this;
    }

    @Override
    public ServiceOrderRecord value3(LocalDate value) {
        setEndDate(value);
        return this;
    }

    @Override
    public ServiceOrderRecord value4(String value) {
        setFinishedPicture(value);
        return this;
    }

    @Override
    public ServiceOrderRecord value5(Integer value) {
        setPersonId(value);
        return this;
    }

    @Override
    public ServiceOrderRecord value6(Integer value) {
        setBuildingId(value);
        return this;
    }

    @Override
    public ServiceOrderRecord value7(Integer value) {
        setServiceId(value);
        return this;
    }

    @Override
    public ServiceOrderRecord value8(Integer value) {
        setOrderId(value);
        return this;
    }

    @Override
    public ServiceOrderRecord values(Integer value1, LocalDate value2, LocalDate value3, String value4, Integer value5, Integer value6, Integer value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ServiceOrderRecord
     */
    public ServiceOrderRecord() {
        super(ServiceOrder.SERVICE_ORDER);
    }

    /**
     * Create a detached, initialised ServiceOrderRecord
     */
    public ServiceOrderRecord(Integer id, LocalDate startDate, LocalDate endDate, String finishedPicture, Integer personId, Integer buildingId, Integer serviceId, Integer orderId) {
        super(ServiceOrder.SERVICE_ORDER);

        setId(id);
        setStartDate(startDate);
        setEndDate(endDate);
        setFinishedPicture(finishedPicture);
        setPersonId(personId);
        setBuildingId(buildingId);
        setServiceId(serviceId);
        setOrderId(orderId);
    }
}
